#!/bin/sh

mountpoint -q /proc || mount -t proc proc /proc
mountpoint -q /sys || mount -t sysfs sysfs /sys
mkdir -p /sys/fs/cgroup
mountpoint -q /sys/fs/cgroup || mount -t cgroup2 cgroup2 /sys/fs/cgroup
mountpoint -q /dev || mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts /dev/shm /run

mountpoint -q /dev/pts || mount -t devpts -o gid=5,mode=620 devpts /dev/pts
mountpoint -q /dev/shm || mount -t tmpfs tmpfs /dev/shm
mountpoint -q /run || mount -t tmpfs tmpfs /run

mount -o remount,rw /
mount -a
swapon -a

. /etc/profile

if [ -r /etc/hostname ]; then
IFS= read -r hostname < /etc/hostname
echo "$hostname" > /proc/sys/kernel/hostname
fi

for tty in tty2 tty3; do
  (while true; do /usr/bin/agetty "$tty" 38400 linux; sleep 1; done) &
done

exec </dev/null >/dev/null 2>&1

mkdir -p /run/service
for svc in /etc/s6/sv/*; do
	[ -e "$svc" ] || continue
	ln -sfn "$svc" "/run/service/$(basename "$svc")"
done

exec /usr/bin/s6-svscan /run/service
